#!/usr/bin/env python3
"""
VOLT AI Watch - Setup Wizard
Generates config.h file from user input
"""

import os
import sys


def print_header():
    print("=" * 60)
    print("⚡ VOLT AI Watch - Setup Wizard")
    print("=" * 60)
    print()
    print("This wizard will help you create a config.h file")
    print("for your VOLT watch with your child's information.")
    print()


def get_input(prompt, default="", required=True):
    """Get user input with optional default value"""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "

    while True:
        value = input(full_prompt).strip()
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("❌ This field is required. Please enter a value.")


def get_yes_no(prompt, default=True):
    """Get yes/no input"""
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{prompt} [{default_str}]: ").strip().lower()
        if response in ["y", "yes"]:
            return True
        elif response in ["n", "no"]:
            return False
        elif response == "":
            return default
        else:
            print("❌ Please enter 'y' or 'n'")


def main():
    print_header()

    # Section 1: Child Information
    print("📝 SECTION 1: Child Information")
    print("-" * 60)
    child_name = get_input("Child's name (e.g., Emma)")
    child_age = get_input("Child's age (e.g., 8)")
    print()

    # Section 2: WiFi Settings
    print("📶 SECTION 2: WiFi Settings")
    print("-" * 60)
    print("Note: VOLT only works with 2.4GHz WiFi (not 5GHz)")
    wifi_ssid = get_input("WiFi network name")
    wifi_password = get_input("WiFi password")

    add_backup = get_yes_no("Add backup WiFi network?", False)
    wifi_ssid_2 = ""
    wifi_password_2 = ""
    if add_backup:
        wifi_ssid_2 = get_input("Backup WiFi name", required=False)
        if wifi_ssid_2:
            wifi_password_2 = get_input("Backup WiFi password", required=False)
    print()

    # Section 3: OpenAI API Key
    print("🔑 SECTION 3: OpenAI API Key")
    print("-" * 60)
    print("Get your API key from: https://platform.openai.com/api-keys")
    print("Cost: Typically $0.01-0.05 per conversation")
    api_key = get_input("OpenAI API key (starts with 'sk-')")
    print()

    # Section 4: Voice Settings
    print("🎤 SECTION 4: Voice Settings")
    print("-" * 60)
    print("Available voices:")
    print("  1. echo    - Male, warm, conversational (DEFAULT)")
    print("  2. nova    - Female, bright, energetic")
    print("  3. fable   - Male, warm, storytelling")
    print("  4. shimmer - Female, soft, gentle")
    print("  5. alloy   - Neutral, smooth")
    print("  6. onyx    - Male, deep, authoritative")

    voice_choice = get_input("Choose voice (1-6)", "1")
    voices = ["echo", "nova", "fable", "shimmer", "alloy", "onyx"]
    voice_index = (
        int(voice_choice) - 1
        if voice_choice.isdigit() and 1 <= int(voice_choice) <= 6
        else 0
    )
    tts_voice = voices[voice_index]

    tts_speed = get_input("Voice speed (0.25-4.0, recommended: 1.08)", "1.08")
    print()

    # Section 5: Custom Messages
    print("💬 SECTION 5: Custom Messages (Optional)")
    print("-" * 60)
    customize = get_yes_no("Customize love message?", False)
    if customize:
        love_message = get_input(
            "Love message",
            f"💙 Dad loves you so much, {child_name}! You make every day brighter! 🌟",
        )
    else:
        love_message = (
            f"💙 Dad loves you so much, {child_name}! You make every day brighter! 🌟"
        )
    print()

    # Generate config.h
    print("✨ Generating config.h...")

    config_content = f"""// ============================================
// VOLT AI Watch - Configuration
// Generated by Setup Wizard
// ============================================

#ifndef CONFIG_H
#define CONFIG_H

// ============================================
// CHILD INFORMATION
// ============================================
const char* CHILD_NAME = "{child_name}";
const int CHILD_AGE = {child_age};

// ============================================
// WIFI SETTINGS
// ============================================
const char* WIFI_SSID = "{wifi_ssid}";
const char* WIFI_PASSWORD = "{wifi_password}";

const char* WIFI_SSID_2 = "{wifi_ssid_2}";
const char* WIFI_PASSWORD_2 = "{wifi_password_2}";

const char* WIFI_SSID_3 = "";
const char* WIFI_PASSWORD_3 = "";

// ============================================
// OPENAI API KEY
// ============================================
const char* OPENAI_API_KEY = "{api_key}";

// ============================================
// VOICE SETTINGS
// ============================================
const char* TTS_VOICE = "{tts_voice}";
const float TTS_SPEED = {tts_speed};

// ============================================
// PERSONALITY SETTINGS
// ============================================
const char* VOLT_PERSONALITY = 
    "You are VOLT, a caring AI companion watch created by Dad. "
    "You speak warmly and encouragingly to {child_name}. "
    "Keep responses short (2-3 sentences max). "
    "Be supportive, kind, and age-appropriate for a {child_age} year old. "
    "Use simple language and be positive.";

// ============================================
// CUSTOM MESSAGES
// ============================================
const char* LOVE_MESSAGE = "{love_message}";

const char* MORNING_GREETING = 
    "Good morning, {child_name}! Ready for an amazing day? ☀️";

const char* BEDTIME_MESSAGE = 
    "Sweet dreams, {child_name}! Dad loves you! 💙🌙";

const char* OFFLINE_MESSAGE = 
    "VOLT is offline right now. Try the breathing exercise or jokes! 😊";

// ============================================
// BUTTON BEHAVIOR
// ============================================
const bool ENABLE_VOICE_CHAT = true;
const bool ENABLE_JOKES = true;
const bool ENABLE_BREATHING = true;
const bool ENABLE_LOVE_MESSAGE = true;
const bool ENABLE_WIFI_SETUP = true;

// ============================================
// ADVANCED SETTINGS
// ============================================
const int WIFI_TIMEOUT = 20;
const int MAX_RECORDING_TIME = 5;
const int SLEEP_TIMEOUT = 5;
const int DISPLAY_BRIGHTNESS = 200;

const char* AI_MODEL = "gpt-4o-mini";
const int MAX_TOKENS = 150;
const float AI_TEMPERATURE = 0.7;

const char* TTS_MODEL = "tts-1-hd";
const char* STT_MODEL = "whisper-1";

const char* WEB_PASSWORD = "volt2024";
const char* AP_SSID_PREFIX = "VOLT-Setup-";
const char* AP_PASSWORD = "volt2024";

// ============================================
// SAFETY SETTINGS
// ============================================
const bool ENABLE_CONTENT_FILTER = true;
const bool BLOCK_VIOLENCE = true;
const bool BLOCK_ADULT_CONTENT = true;
const int MAX_CONVERSATION_TURNS = 10;

#endif // CONFIG_H
"""

    # Write to file
    try:
        with open("config.h", "w", encoding="utf-8") as f:
            f.write(config_content)
        print()
        print("=" * 60)
        print("✅ SUCCESS! config.h has been created!")
        print("=" * 60)
        print()
        print("📋 Summary:")
        print(f"   Child: {child_name}, age {child_age}")
        print(f"   WiFi: {wifi_ssid}")
        print(f"   Voice: {tts_voice}")
        print(f"   API Key: {api_key[:10]}...")
        print()
        print("🚀 Next Steps:")
        print("   1. Open this folder in VSCode")
        print("   2. Connect your VOLT watch via USB")
        print("   3. Click the Upload button (→) at the bottom")
        print("   4. Wait for flashing to complete")
        print("   5. Enjoy VOLT!")
        print()
        print("Need help? See COMPLETE_SETUP_GUIDE.md")
        print("=" * 60)

    except Exception as e:
        print(f"❌ Error writing config.h: {e}")
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
